baseURL: https://woadey.github.io/
languageCode: en-us
paginate: 5
title: woadey
theme: PaperMod

# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false

googleAnalytics: G-EF924K1NXR

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: woadeyblog
  description: "cybersec ctf blog"
  keywords: [Blog, Home]
  # author: ["Me", "You"] # multiple authors
  images: ["https://static.scientificamerican.com/sciam/cache/file/7A715AD8-449D-4B5A-ABA2C5D92D9B5A21_source.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: false # removes users ability to toggle

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false # hides summary in /posts
  showtoc: true # shows TOC on post
  tocopen: false # opens TOC by default

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/favicon.ico"

  label:
    text: "oadey" # top left
    icon: "favicon/apple-touch-icon.png" # icon next to Home label
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "woadey"
    subtitle: "my blog to store all things cybersec"
    imageUrl: "img/itachi.png" # img url works too
    imageWidth: 200
    imageHeight: 200
    # imageTitle: profile_pic
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    # - name: twitter
      # url: "https://twitter.com/"
    # - name: stackoverflow
      # url: "https://stackoverflow.com"
    - name: twitter
      url: https://twitter.com/woadey_
    - name: discord
      url: https://discord.com/users/woadey#3386
    - name: github
      url: "https://github.com/woadey"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/woadey/woadey.github.io/tree/main/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 1
    - identifier: categories
      name: categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: tags
      url: /tags/
      weight: 3
    - identifier: search
      name: search
      url: /search/
      weight: 5
    - identifier: archive
      name: archive
      url: /archives/
      weight: 4

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true # allows you to jump to line no's
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai