baseURL: https://woadey.lol/
languageCode: en-us
paginate: 5
title: woadey
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
googleAnalytics: G-EF924K1NXR

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

social:
  twitter: "woadey_"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: woadey's blog
  description: "my blog to store all things cybersec"
  keywords: [Blog, Home, ctf, cybersec, infosec]
  # author: ["Me", "You"] # multiple authors
  images: ["favicon/white_pink_bg/apple-touch-icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: false # removes users ability to toggle

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false # hides summary in /posts
  showtoc: true # shows TOC on post
  tocopen: false # opens TOC by default

  assets:
    disableHLJS: true
    # disableFingerprinting: true
    favicon: "favicon/pink_trans_bg/favicon.ico"
    favicon16x16: "favicon/pink_trans_bg/favicon-16x16.png"
    favicon32x32: "favicon/pink_trans_bg/favicon-32x32.png"
    apple_touch_icon: "favicon/white_pink_bg/apple-touch-icon.png"
    safari_pinned_tab: "favicon/pink_trans_bg/favicon.ico"

  label:
    text: "oadey" # top left
    icon: "images/pink.jpeg" # icon next to Home label
    iconSize: 32

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    emoji: "\u26A1"
    title: "woadey"
    subtitle: "my blog to store all things cybersec"
    imageUrl: "images/itachi.png" # img url works too
    imageWidth: 350
    imageHeight: 350
    imageTitle: profile_pic
    buttons:
      - name: Posts
        url: posts
      - name: Categories
        url: categories

  csp:
    childsrc: ["'self'"]
    fontsrc: ["'self'"]
    formaction: ["'self'"]
    framesrc: ["'self'"]
    imgsrc: ["'self'","data:","https://*.google-analytics.com", "https://*.googletagmanager.com"]
    objectsrc: ["'none'"]
    stylesrc: ["'self'", "'unsafe-inline'"]
    scriptsrc: ["'self'", "'unsafe-inline'", "https://*.googletagmanager.com"]
    prefetchsrc: ["'self'"]
    connectsrc: ["'self'", "https://*.google-analytics.com", "https://*.analytics.google.com", "https://*.googletagmanager.com"]
  
  socialIcons:
    - name: twitter
      url: https://twitter.com/woadey_
    - name: discord
      url: https://discord.com/users/woadey#3386
    - name: github
      url: "https://github.com/woadey"
    - name: mastodon
      url: "https://infosec.exchange/@woadey"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]
    
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 1
    - identifier: categories
      name: categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: tags
      url: /tags/
      weight: 3
    - identifier: archives
      name: archives
      url: /archives/
      weight: 4
    - identifier: search
      name: search
      url: /search/
      weight: 5

pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: false

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5